name: DevSpace CLI Install
author: loft.sh
description: Installs the devspace CLI
inputs:
  version:
    description: 'The version of devspace to install'
    required: false
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
